### ISSUE TITLE
How to handle cron triggers in worker?

### ISSUE THREAD

**Issue by Boscop** [BrandonDyer64/leptos-workers#2]
Thanks for this example repo :)

Cloudflare workers have the ability to not just be called based on incoming HTTP requests but also based on cron triggers:
https://developers.cloudflare.com/workers/configuration/cron-triggers/
https://developers.cloudflare.com/workers/examples/multiple-cron-triggers/

In JS this can easily be done by having an exported function named `scheduled` that gets called for cron triggers.

How can I handle cron triggers in a Rust/leptos based app, based on this template? :)

**Comment by bakcxoj** [comment]
You can specify different kinds of events in your `lib.rs` file. Have a look at this documentation:
https://docs.rs/worker/0.3.4/worker/attr.event.html

**Comment by Boscop** [comment]
Thanks!
